@startuml
' ---- Layout & Stil ----
hide empty methods
 
' ---- Legende ----
legend right
<<RichType>>: Stark typisierte Primitive
<<ValueObject>>: Value Objects
<<entity>>: Persistente Entität
<<unique>>: Eindeutige Einschränkung auf Spaltenebene
<<nn>>: Not null
endlegend
 
' ===================== Packages =====================

package "Shared\n(Value Objects)" as P_Shared #EEF6FF {
 
  class Phone << (R,#FFEECC) RichType >> {
    +Value: string <<nn>>
  }
}

class User {}

class Customer {}

enum OrderStatus {
  SUBMITTED
  CONFIRMED
  PREPARING
  DELIVERED
  CANCELLED
}

class Order {
  Customer: Customer <<nn>>
  Restaurant: Restaurant <<nn>>
  OrderedAt: DateTime <<nn>>
  OrderState: OrderState <<nn>>
}

class OrderItem {
  Order: Order <<nn>>
  MenuItem: MenuItem <<nn>>
  Quantity: int <<nn>>
  Price: decimal <<nn>>
}

class RestaurantOwner {}

class Restaurant {
  Name: string <<nn>>
  RestaurantOwner: RestaurantOwner <<nn>>
}

class MenuItem {
  Restaurant: Restaurant <<nn>>
  Name: string <<nn>>
  Price: decimal <<nn>>
}

class Cart {
   Customer: Customer <<nn>>
   Restaurant: Restaurant <<nn>>
   CartItems: List<CartItem> <<nn>>
}

class CartItem {
   Cart: Cart <<nn>>
   MenuItem: MenuItem <<nn>>
   Quantity: int <<nn>>
}


'Beziehungen


' ===================== Beziehungen =====================

Customer "1" <-- "*" Order



@enduml