@startuml
' ---- Layout & Stil ----
hide empty methods
 
' ---- Legende ----
legend right
<<RichType>>: Stark typisierte Primitive
<<ValueObject>>: Value Objects
<<entity>>: Persistente Entität
<<unique>>: Eindeutige Einschränkung auf Spaltenebene
<<nn>>: Not null
endlegend
 
' ===================== Packages =====================

package "Shared\n(Value Objects)" as P_Shared #EEF6FF {
 
  class Phone << (R,#FFEECC) RichType >> {
    +Value: string <<nn>>
  }
}

class User {}

class Customer {}

class RestaurantOwner {}

class Order {
 Customer: Customer <<nn>>
}

class OrderItem {}

class Restaurant {}

class MenuItem {}


'Beziehungen


' ===================== Beziehungen =====================

Customer "1" <-- "*" Order



@enduml